/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import negocio.Categoria;
import negocio.Despesa;
import persistencia.DespesaDAO;

/**
 *
 * @author gustavo
 */
public class Tela extends javax.swing.JFrame {

    private Categoria categoria;
    private double valor;
    private String descricao;

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        this.setTitle("Controle Financeiro");

        DespesaDAO.recuperaDados();
        tfTotalAtual.setText("R$ " + DespesaDAO.totalDespesas());

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbControleFinanceiro = new javax.swing.JLabel();
        cbCategorias = new javax.swing.JComboBox<>();
        lbDespesas = new javax.swing.JLabel();
        lbEscolhaCategoria = new javax.swing.JLabel();
        btMostrarDespesasCategoria = new javax.swing.JButton();
        lbValor = new javax.swing.JLabel();
        tfValor = new javax.swing.JTextField();
        btAddDespesa = new javax.swing.JButton();
        btSalvarESair = new javax.swing.JButton();
        tfDescricao = new javax.swing.JTextField();
        lbDescricao = new javax.swing.JLabel();
        btZerarDespesas = new javax.swing.JButton();
        lvTotalAtual = new javax.swing.JLabel();
        tfTotalAtual = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDespesasCategoria = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbControleFinanceiro.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lbControleFinanceiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbControleFinanceiro.setText("Controle Financeiro");

        cbCategorias.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        cbCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentação", "Lazer", "Vestuário", "Transporte", "Educação", "Outras" }));
        cbCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriasActionPerformed(evt);
            }
        });

        lbDespesas.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lbDespesas.setText("DESPESAS");

        lbEscolhaCategoria.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        lbEscolhaCategoria.setText("Escolha a categoria:");

        btMostrarDespesasCategoria.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btMostrarDespesasCategoria.setText("Mostrar despesas desta categoria");
        btMostrarDespesasCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarDespesasCategoriaActionPerformed(evt);
            }
        });

        lbValor.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        lbValor.setText("Valor:");

        tfValor.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        tfValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValorActionPerformed(evt);
            }
        });

        btAddDespesa.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btAddDespesa.setText("Adicionar despesa");
        btAddDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddDespesaActionPerformed(evt);
            }
        });

        btSalvarESair.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btSalvarESair.setText("Salvar e Sair");
        btSalvarESair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarESairActionPerformed(evt);
            }
        });

        tfDescricao.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N

        lbDescricao.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        lbDescricao.setText("Descrição:");

        btZerarDespesas.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btZerarDespesas.setText("Zerar despesas");
        btZerarDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btZerarDespesasActionPerformed(evt);
            }
        });

        lvTotalAtual.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        lvTotalAtual.setText("Total atual:");

        tfTotalAtual.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        tfTotalAtual.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tfTotalAtualInputMethodTextChanged(evt);
            }
        });
        tfTotalAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalAtualActionPerformed(evt);
            }
        });

        taDespesasCategoria.setColumns(20);
        taDespesasCategoria.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        taDespesasCategoria.setRows(5);
        jScrollPane1.setViewportView(taDespesasCategoria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbControleFinanceiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDespesas)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lvTotalAtual)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfTotalAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbEscolhaCategoria)
                                        .addComponent(lbValor)
                                        .addComponent(lbDescricao))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfValor, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cbCategorias, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfDescricao, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btAddDespesa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                        .addComponent(btZerarDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btMostrarDespesasCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(btSalvarESair)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbControleFinanceiro)
                .addGap(18, 18, 18)
                .addComponent(lbDespesas)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btMostrarDespesasCategoria))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbValor))
                                        .addGap(18, 18, 18)
                                        .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbDescricao))
                                .addGap(62, 62, 62)
                                .addComponent(btAddDespesa)
                                .addGap(18, 18, 18)
                                .addComponent(btZerarDespesas))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lbEscolhaCategoria))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTotalAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lvTotalAtual))
                .addGap(18, 18, 18)
                .addComponent(btSalvarESair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbCategoriasActionPerformed

    private void tfValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfValorActionPerformed

    private void btSalvarESairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarESairActionPerformed
        // TODO add your handling code here:
        DespesaDAO.salvaDados();
        System.exit(0);
    }//GEN-LAST:event_btSalvarESairActionPerformed

    private void btMostrarDespesasCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarDespesasCategoriaActionPerformed
        // TODO add your handling code here:
        switch (cbCategorias.getSelectedIndex()) {

            case 0:
                categoria = Categoria.ALIMENTACAO;
                break;

            case 1:
                categoria = Categoria.LAZER;
                break;

            case 2:
                categoria = Categoria.VESTUARIO;
                break;

            case 3:
                categoria = Categoria.TRANSPORTE;
                break;

            case 4:
                categoria = Categoria.EDUCACAO;
                break;

            case 5:
                categoria = Categoria.OUTRAS;
                break;
        }
        
        taDespesasCategoria.setText(DespesaDAO.totalDespesasMes(categoria));
    }//GEN-LAST:event_btMostrarDespesasCategoriaActionPerformed

    private void tfTotalAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalAtualActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_tfTotalAtualActionPerformed

    private void tfTotalAtualInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tfTotalAtualInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalAtualInputMethodTextChanged

    private void btAddDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddDespesaActionPerformed
        // TODO add your handling code here:
        switch (cbCategorias.getSelectedIndex()) {

            case 0:
                categoria = Categoria.ALIMENTACAO;
                break;

            case 1:
                categoria = Categoria.LAZER;
                break;

            case 2:
                categoria = Categoria.VESTUARIO;
                break;

            case 3:
                categoria = Categoria.TRANSPORTE;
                break;

            case 4:
                categoria = Categoria.EDUCACAO;
                break;

            case 5:
                categoria = Categoria.OUTRAS;
                break;
        }

        valor = Double.parseDouble(tfValor.getText());
        descricao = tfDescricao.getText();

        DespesaDAO.create(new Despesa(valor, categoria, descricao));
        
        tfTotalAtual.setText("R$ " + DespesaDAO.totalDespesas());
        tfValor.setText("");
        tfDescricao.setText("");
       
        
        


    }//GEN-LAST:event_btAddDespesaActionPerformed

    private void btZerarDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btZerarDespesasActionPerformed
        // TODO add your handling code here:
        DespesaDAO.zerarDespesas();
        tfTotalAtual.setText("R$ " + DespesaDAO.totalDespesas());
    }//GEN-LAST:event_btZerarDespesasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddDespesa;
    private javax.swing.JButton btMostrarDespesasCategoria;
    private javax.swing.JButton btSalvarESair;
    private javax.swing.JButton btZerarDespesas;
    private javax.swing.JComboBox<String> cbCategorias;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbControleFinanceiro;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbDespesas;
    private javax.swing.JLabel lbEscolhaCategoria;
    private javax.swing.JLabel lbValor;
    private javax.swing.JLabel lvTotalAtual;
    private javax.swing.JTextArea taDespesasCategoria;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JTextField tfTotalAtual;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables
}
