/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import negocio.Lixeira;
import persistencia.LixeiraDAO;

/**
 *
 * @author gustavo
 */
public class Tela extends javax.swing.JFrame {

    private double altura;
    private double raio;

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbRaio = new javax.swing.JLabel();
        lbAltura = new javax.swing.JLabel();
        lbCriar = new javax.swing.JLabel();
        tfRaio = new javax.swing.JTextField();
        tfAltura = new javax.swing.JTextField();
        btEnviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbArea = new javax.swing.JLabel();
        lbVolumeMaximo = new javax.swing.JLabel();
        tfArea = new javax.swing.JTextField();
        tfVolumeMaximo = new javax.swing.JTextField();
        btEnviar1 = new javax.swing.JButton();
        tfVolumeAtual = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lbVolumeAtual = new javax.swing.JLabel();
        lbInfos = new javax.swing.JLabel();
        lbInfos1 = new javax.swing.JLabel();
        btEncher = new javax.swing.JButton();
        btEsvaziar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btRecuperar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbRaio.setText("Raio:");

        lbAltura.setText("Altura:");

        lbCriar.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lbCriar.setText("Criar Lixeira");

        tfRaio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRaioActionPerformed(evt);
            }
        });

        tfAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAlturaActionPerformed(evt);
            }
        });

        btEnviar.setText("Enviar Dados");
        btEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarActionPerformed(evt);
            }
        });

        jLabel1.setText("cm");

        jLabel3.setText("cm");

        jLabel4.setText("cm²");

        jLabel5.setText("cm³");

        lbArea.setText("Área:");

        lbVolumeMaximo.setText("Volume Máximo:");

        tfArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAreaActionPerformed(evt);
            }
        });

        tfVolumeMaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfVolumeMaximoActionPerformed(evt);
            }
        });

        btEnviar1.setText("Limpar");
        btEnviar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviar1ActionPerformed(evt);
            }
        });

        tfVolumeAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfVolumeAtualActionPerformed(evt);
            }
        });

        jLabel6.setText("cm³");

        lbVolumeAtual.setText("Volume Atual:");

        lbInfos.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lbInfos.setText("Infos Lixeira");

        lbInfos1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lbInfos1.setText("LIXEIRA");

        btEncher.setText("Encher");
        btEncher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEncherActionPerformed(evt);
            }
        });

        btEsvaziar.setText("Esvaziar");
        btEsvaziar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEsvaziarActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btRecuperar.setText("Recuperar Dados");
        btRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRecuperarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbAltura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(tfAltura))
                                    .addComponent(btEnviar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btEnviar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btRecuperar, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbRaio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfRaio, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 88, Short.MAX_VALUE)
                                        .addComponent(lbVolumeAtual)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfVolumeAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btEncher)
                                .addGap(18, 18, 18)
                                .addComponent(btEsvaziar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbVolumeMaximo)
                                    .addComponent(lbArea))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfArea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfVolumeMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbInfos)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSair)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(lbInfos1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbInfos1)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCriar)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbRaio)
                            .addComponent(tfRaio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAltura)
                            .addComponent(tfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbInfos)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbArea)
                            .addComponent(tfArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbVolumeMaximo)
                            .addComponent(tfVolumeMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEnviar)
                    .addComponent(lbVolumeAtual)
                    .addComponent(tfVolumeAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEnviar1)
                    .addComponent(btEncher)
                    .addComponent(btEsvaziar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair)
                    .addComponent(btRecuperar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfRaioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRaioActionPerformed

    }//GEN-LAST:event_tfRaioActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        if (LixeiraDAO.getLixeira() != null) {
            LixeiraDAO.salvar();
        }
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void tfAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAlturaActionPerformed

    }//GEN-LAST:event_tfAlturaActionPerformed

    private void btEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarActionPerformed
        raio = Double.parseDouble(tfRaio.getText());
        altura = Double.parseDouble(tfAltura.getText());
        Lixeira lixeira = new Lixeira(altura, raio);
        LixeiraDAO.create(lixeira);

        tfArea.setText(LixeiraDAO.getLixeira().area() + "");
        tfVolumeMaximo.setText(LixeiraDAO.getLixeira().volumeMaximo() + "");
        tfVolumeAtual.setText(LixeiraDAO.getLixeira().getVolumeAtual() + "");
    }//GEN-LAST:event_btEnviarActionPerformed

    private void tfAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAreaActionPerformed
        if (LixeiraDAO.getLixeira() != null) {
            tfArea.setText(LixeiraDAO.getLixeira().area() + "");
        }
    }//GEN-LAST:event_tfAreaActionPerformed

    private void tfVolumeMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfVolumeMaximoActionPerformed

    }//GEN-LAST:event_tfVolumeMaximoActionPerformed

    private void tfVolumeAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfVolumeAtualActionPerformed

    }//GEN-LAST:event_tfVolumeAtualActionPerformed

    private void btEncherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEncherActionPerformed
        LixeiraDAO.getLixeira().encher();
        tfVolumeAtual.setText(LixeiraDAO.getLixeira().getVolumeAtual() + "");
    }//GEN-LAST:event_btEncherActionPerformed

    private void btEnviar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviar1ActionPerformed
        tfRaio.setText("");
        tfAltura.setText("");
    }//GEN-LAST:event_btEnviar1ActionPerformed

    private void btEsvaziarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEsvaziarActionPerformed
        LixeiraDAO.getLixeira().esvaziar();
        tfVolumeAtual.setText(LixeiraDAO.getLixeira().getVolumeAtual() + "");
    }//GEN-LAST:event_btEsvaziarActionPerformed

    private void btRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRecuperarActionPerformed
        if (LixeiraDAO.recuperar()) {
            LixeiraDAO.recuperar();
        }
        
        if (LixeiraDAO.getLixeira() != null) {
            tfAltura.setText(LixeiraDAO.getLixeira().getAltura() + "");
            tfRaio.setText(LixeiraDAO.getLixeira().getRaio() + "");
            tfArea.setText(LixeiraDAO.getLixeira().area() + "");
            tfVolumeMaximo.setText(LixeiraDAO.getLixeira().volumeMaximo() + "");
            tfVolumeAtual.setText(LixeiraDAO.getLixeira().getVolumeAtual() + "");
        }
    }//GEN-LAST:event_btRecuperarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEncher;
    private javax.swing.JButton btEnviar;
    private javax.swing.JButton btEnviar1;
    private javax.swing.JButton btEsvaziar;
    private javax.swing.JButton btRecuperar;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbAltura;
    private javax.swing.JLabel lbArea;
    private javax.swing.JLabel lbCriar;
    private javax.swing.JLabel lbInfos;
    private javax.swing.JLabel lbInfos1;
    private javax.swing.JLabel lbRaio;
    private javax.swing.JLabel lbVolumeAtual;
    private javax.swing.JLabel lbVolumeMaximo;
    private javax.swing.JTextField tfAltura;
    private javax.swing.JTextField tfArea;
    private javax.swing.JTextField tfRaio;
    private javax.swing.JTextField tfVolumeAtual;
    private javax.swing.JTextField tfVolumeMaximo;
    // End of variables declaration//GEN-END:variables
}
